language: cpp
compiler:
  - gcc
notifications:
    irc: "irc.freenode.net#freeseer"
virtualenv:
  system_site_packages: true
before_install:  # Prepare system to install prerequisits
  - echo 'yes' | sudo add-apt-repository ppa:gstreamer-developers/ppa
  - echo 'yes' | sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get -qq update
install:  # Install prerequisits
  - sudo apt-get -qq install cmake
  - sudo apt-get -qq install gstreamer1.0*
  - sudo apt-get -qq install qtdeclarative5-dev
before_script:  # Prepare system to build / test (set environment variables)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:  # Build / Run Tests
  - pwd
  - mkdir build && cd build
  - cmake .. && make
